package com.revature;

import java.util.ArrayList;
import java.util.List;

import com.revature.models.Account;
import com.revature.models.Role;
import com.revature.models.User;
import com.revature.repositories.AccountDao;
import com.revature.repositories.IAccountDao;
import com.revature.repositories.UserDao;

public class App {

	public static void main(String[] args) {
		
		User u1 = new User("Batman", "pass", Role.Admin, new ArrayList<Account>());
		
		UserDao ud = new UserDao();
		
//		int returnedPk = ud.insert(u1);
//		
		// test to see if the dummy user we inserted was persisted and returned
		// a primary key generated by the DB.
//		System.out.println(returnedPk);
		
		IAccountDao adao = new AccountDao();
		
		List<Account> accounts = adao.findAll();
		System.out.println(accounts);

		System.out.println(adao.findByOwner(4));
		
		System.out.println("please enter your username");
		
		// scanner gets the username, and password.... and we build a new User obj from the console 
		
		// call our service method to REGISTER it
		
	}

}
